server:
  forward-headers-strategy: framework
  port: '8082'

petapi:
  url: "https://petstore.swagger.io"

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee_db
    username: root
    password: root
    initialization-mode: always
    initialize: true
    continue-on-error: true
  jpa:
    spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.show-sql: true
    spring.jpa.hibernate.ddl-auto: update
    spring.jpa.properties.hibernate.format_sql: true

  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring-doc:
  swagger-ui:
    path: swagger-ui.html

logging:
  level:
    web: TRACE
    org:
      springframework:
        web: TRACE




#spring:
#  h2:
#    console.enabled: true
#    console.path: /h2-console
#    console.setting.trace: false
#  datasource:
#    url: jdbc:h2:mem:mydb #jbdc:h2:file:/data/demo/ if persistence is required for file
#    username: root
#    password: demo
#    driverClassName: org.h2.Driver
#  jpa:
#

